# Generated by Django 4.2.13 on 2024-07-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_userhistory_datevar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='image',
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='datevar',
            field=models.CharField(default='2024-07-25 21:29:08.515792', max_length=100),
        ),
    ]
