# Generated by Django 4.2.13 on 2024-07-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_userhistory_datevar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='datevar',
            field=models.CharField(default='2024-07-26 02:09:33.062281', max_length=100),
        ),
    ]
