# Generated by Django 4.2.13 on 2024-08-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_userhistory_datevar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='datevar',
            field=models.CharField(default='2024-08-27 09:59:03.247003', max_length=100),
        ),
    ]
