# Generated by Django 4.2.13 on 2024-09-13 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_userhistory_datevar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='availablequantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='datevar',
            field=models.CharField(default='2024-09-13 19:25:20.800012', max_length=100),
        ),
    ]
