# Generated by Django 4.2.13 on 2024-09-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_item_availablequantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='announcement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='datevar',
            field=models.CharField(default='2024-09-25 18:55:37.926854', max_length=100),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
