# Generated by Django 4.2.13 on 2024-09-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_category_announcement_alter_userhistory_datevar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='datevar',
            field=models.CharField(default='2024-09-25 19:07:07.421419', max_length=100),
        ),
    ]
