# Generated by Django 4.2.13 on 2024-09-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_userhistory_datevar_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='datevar',
            field=models.CharField(default='2024-09-25 20:48:25.731021', max_length=100),
        ),
    ]
