# Generated by Django 4.2.13 on 2024-09-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_userhistory_datevar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expiry',
            old_name='expiry',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='datevar',
            field=models.CharField(default='2024-09-25 21:13:47.750260', max_length=100),
        ),
    ]
