# Generated by Django 4.2.13 on 2024-09-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_rename_expiry_expiry_date_alter_userhistory_datevar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='makecategory',
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='datevar',
            field=models.CharField(default='2024-09-25 21:21:17.376866', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='makecategory',
            field=models.ManyToManyField(related_name='items', to='mainapp.category'),
        ),
    ]
