# Generated by Django 4.2.13 on 2024-09-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_remove_item_makecategory_alter_userhistory_datevar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='makecategory',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='datevar',
            field=models.CharField(default='2024-09-25 21:32:06.448138', max_length=100),
        ),
    ]
