# Generated by Django 4.2.13 on 2024-10-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_alter_userhistory_datevar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='datevar',
            field=models.CharField(default='2024-10-03 16:50:48.588479', max_length=100),
        ),
    ]
