# Generated by Django 4.2.13 on 2024-10-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_alter_userhistory_datevar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='availablequantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='datevar',
            field=models.CharField(default='2024-10-26 21:04:12.720372', max_length=100),
        ),
    ]
