# Generated by Django 4.2.13 on 2024-11-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_alter_item_availablequantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='datevar',
            field=models.CharField(default='2024-11-04 18:49:39.359728', max_length=100),
        ),
    ]
