# Generated by Django 4.2.13 on 2024-11-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_alter_userhistory_datevar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='datevar',
            field=models.CharField(default='2024-11-04 18:50:51.861292', max_length=100),
        ),
    ]
